import type {
  Incident,
  AgentInfo,
  RCAReport,
  LearningMetrics,
  DashboardStats,
} from "./types";

// ─── Incidents ────────────────────────────────────────────────────────────────

export const MOCK_INCIDENTS: Incident[] = [
  {
    id: "inc-2041-a1b2c3d4",
    title: "Payment service high error rate — 503s spiking",
    description:
      "The payment-service is returning HTTP 503 errors at a rate of 42%. Downstream order-service is timing out. Revenue impact estimated at $18k/min.",
    severity: "P1",
    status: "investigating",
    created_at: new Date(Date.now() - 12 * 60 * 1000).toISOString(),
    updated_at: new Date(Date.now() - 2 * 60 * 1000).toISOString(),
    affected_services: ["payment-service", "order-service", "checkout-ui"],
    assigned_agents: ["log_analyzer", "metric_analyzer", "rca_synthesizer"],
    investigation_id: "inv-mock-001",
  },
  {
    id: "inc-2040-e5f6g7h8",
    title: "Database connection pool exhaustion — auth-service",
    description:
      "auth-service is exhausting its PostgreSQL connection pool. p99 query latency has risen to 4.2s, causing login timeouts.",
    severity: "P2",
    status: "investigating",
    created_at: new Date(Date.now() - 45 * 60 * 1000).toISOString(),
    updated_at: new Date(Date.now() - 5 * 60 * 1000).toISOString(),
    affected_services: ["auth-service", "user-service"],
    assigned_agents: ["log_analyzer", "metric_analyzer", "fix_recommender"],
    investigation_id: "inv-mock-002",
  },
  {
    id: "inc-2039-i9j0k1l2",
    title: "CDN cache invalidation loop causing origin overload",
    description:
      "Faulty cache invalidation rules pushed at 14:20 UTC are causing cache misses for all static assets, overwhelming the origin servers.",
    severity: "P2",
    status: "resolved",
    created_at: new Date(Date.now() - 3 * 60 * 60 * 1000).toISOString(),
    updated_at: new Date(Date.now() - 30 * 60 * 1000).toISOString(),
    resolved_at: new Date(Date.now() - 30 * 60 * 1000).toISOString(),
    affected_services: ["cdn", "asset-server", "web-frontend"],
    assigned_agents: ["log_analyzer", "trace_analyzer", "rca_synthesizer", "fix_recommender"],
    rca_id: "rca-mock-001",
  },
  {
    id: "inc-2038-m3n4o5p6",
    title: "Memory leak in recommendation-engine workers",
    description:
      "recommendation-engine Kubernetes pods are OOMKilling every ~2 hours due to a memory leak in the ML model loading path.",
    severity: "P3",
    status: "open",
    created_at: new Date(Date.now() - 6 * 60 * 60 * 1000).toISOString(),
    updated_at: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
    affected_services: ["recommendation-engine", "api-gateway"],
    assigned_agents: [],
  },
  {
    id: "inc-2037-q7r8s9t0",
    title: "Elasticsearch cluster split-brain — search degraded",
    description:
      "Search cluster experienced a split-brain event after a network partition. Stale results being served. Re-election in progress.",
    severity: "P2",
    status: "resolved",
    created_at: new Date(Date.now() - 24 * 60 * 60 * 1000).toISOString(),
    updated_at: new Date(Date.now() - 20 * 60 * 60 * 1000).toISOString(),
    resolved_at: new Date(Date.now() - 20 * 60 * 60 * 1000).toISOString(),
    affected_services: ["elasticsearch", "search-service", "product-catalog"],
    assigned_agents: ["log_analyzer", "dependency_mapper", "rca_synthesizer"],
    rca_id: "rca-mock-002",
  },
  {
    id: "inc-2036-u1v2w3x4",
    title: "Kafka consumer lag spike — notification pipeline delayed",
    description:
      "Notification pipeline consumer group is 45 minutes behind. Users are receiving delayed push notifications and emails.",
    severity: "P3",
    status: "resolved",
    created_at: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
    updated_at: new Date(Date.now() - 40 * 60 * 60 * 1000).toISOString(),
    resolved_at: new Date(Date.now() - 40 * 60 * 60 * 1000).toISOString(),
    affected_services: ["kafka", "notification-service"],
    assigned_agents: ["metric_analyzer", "log_analyzer"],
    rca_id: "rca-mock-003",
  },
  {
    id: "inc-2035-y5z6a7b8",
    title: "Slow GraphQL resolver — product details page 5s load",
    description:
      "The product detail page GraphQL resolver is making N+1 database queries, causing 5s+ load times during peak traffic.",
    severity: "P3",
    status: "closed",
    created_at: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
    updated_at: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
    resolved_at: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
    affected_services: ["graphql-gateway", "product-service"],
    assigned_agents: ["trace_analyzer", "fix_recommender"],
    rca_id: "rca-mock-004",
  },
  {
    id: "inc-2034-c9d0e1f2",
    title: "SSL certificate expiry — analytics subdomain down",
    description:
      "SSL certificate for analytics.example.com expired, causing HTTPS errors for all analytics dashboard users.",
    severity: "P4",
    status: "closed",
    created_at: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
    updated_at: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
    resolved_at: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
    affected_services: ["analytics-frontend"],
    assigned_agents: [],
  },
];

// ─── Dashboard stats ──────────────────────────────────────────────────────────

export const MOCK_DASHBOARD_STATS: DashboardStats = {
  total_open: 3,
  by_severity: { P1: 1, P2: 1, P3: 1, P4: 0 },
  active_investigations: 2,
  resolved_today: 1,
  avg_mttr_minutes: 47,
  system_health: "degraded",
};

// ─── Agents ───────────────────────────────────────────────────────────────────

export const MOCK_AGENTS: AgentInfo[] = [
  {
    type: "orchestrator",
    display_name: "Orchestrator",
    description: "Coordinates the entire investigation workflow, dispatching specialized agents in the optimal order.",
    icon: "bot",
    last_run: new Date(Date.now() - 12 * 60 * 1000).toISOString(),
    total_runs: 214,
    success_rate: 0.97,
    avg_duration_ms: 45000,
    status: "running",
    findings_count: 0,
  },
  {
    type: "log_analyzer",
    display_name: "Log Analyzer",
    description: "Scans application logs for error patterns, stack traces, and anomalies correlated with the incident window.",
    icon: "file-text",
    last_run: new Date(Date.now() - 12 * 60 * 1000).toISOString(),
    total_runs: 198,
    success_rate: 0.94,
    avg_duration_ms: 8200,
    status: "running",
    findings_count: 423,
  },
  {
    type: "metric_analyzer",
    display_name: "Metric Analyzer",
    description: "Analyzes Prometheus/Datadog metrics to identify latency spikes, error rate increases, and resource saturation.",
    icon: "bar-chart",
    last_run: new Date(Date.now() - 15 * 60 * 1000).toISOString(),
    total_runs: 201,
    success_rate: 0.96,
    avg_duration_ms: 5600,
    status: "idle",
    findings_count: 381,
  },
  {
    type: "trace_analyzer",
    display_name: "Trace Analyzer",
    description: "Examines distributed traces in Jaeger/Zipkin to identify slow spans, failed requests, and bottlenecks.",
    icon: "git-branch",
    last_run: new Date(Date.now() - 20 * 60 * 1000).toISOString(),
    total_runs: 167,
    success_rate: 0.91,
    avg_duration_ms: 7400,
    status: "idle",
    findings_count: 298,
  },
  {
    type: "dependency_mapper",
    display_name: "Dependency Mapper",
    description: "Maps service call graphs and identifies upstream/downstream services affected by the incident.",
    icon: "network",
    last_run: new Date(Date.now() - 45 * 60 * 1000).toISOString(),
    total_runs: 143,
    success_rate: 0.98,
    avg_duration_ms: 3100,
    status: "idle",
    findings_count: 215,
  },
  {
    type: "hypothesis_generator",
    display_name: "Hypothesis Generator",
    description: "Uses LLM reasoning to generate and rank root cause hypotheses based on collected evidence.",
    icon: "lightbulb",
    last_run: new Date(Date.now() - 12 * 60 * 1000).toISOString(),
    total_runs: 156,
    success_rate: 0.88,
    avg_duration_ms: 12000,
    status: "idle",
    findings_count: 312,
  },
  {
    type: "evidence_collector",
    display_name: "Evidence Collector",
    description: "Gathers supporting evidence for hypotheses — config changes, deployments, runbooks, and similar incidents.",
    icon: "search",
    last_run: new Date(Date.now() - 12 * 60 * 1000).toISOString(),
    total_runs: 142,
    success_rate: 0.92,
    avg_duration_ms: 9800,
    status: "degraded",
    findings_count: 287,
  },
  {
    type: "rca_synthesizer",
    display_name: "RCA Synthesizer",
    description: "Synthesizes all findings into a structured RCA report with root cause, contributing factors, and timeline.",
    icon: "file-check",
    last_run: new Date(Date.now() - 35 * 60 * 1000).toISOString(),
    total_runs: 128,
    success_rate: 0.95,
    avg_duration_ms: 18000,
    status: "idle",
    findings_count: 128,
  },
  {
    type: "fix_recommender",
    display_name: "Fix Recommender",
    description: "Generates actionable fix recommendations with steps, ownership, and estimated effort/impact.",
    icon: "wrench",
    last_run: new Date(Date.now() - 35 * 60 * 1000).toISOString(),
    total_runs: 119,
    success_rate: 0.93,
    avg_duration_ms: 11000,
    status: "idle",
    findings_count: 357,
  },
];

// ─── RCA Report mock ──────────────────────────────────────────────────────────

export const MOCK_RCA_REPORT: RCAReport = {
  id: "rca-mock-001",
  incident_id: "inc-2039-i9j0k1l2",
  investigation_id: "inv-mock-003",
  generated_at: new Date(Date.now() - 28 * 60 * 1000).toISOString(),
  confidence_score: 0.91,
  root_cause: {
    title: "Faulty cache invalidation regex matching all asset paths",
    description:
      "A misconfigured cache invalidation rule deployed at 14:20 UTC used a wildcard regex `.*\\.` that matched all file extensions rather than the intended `.css` extension. This caused every CDN cache node to immediately purge all cached static assets simultaneously, resulting in 100% cache misses and overwhelming the origin servers with traffic they had never been designed to handle cold.",
    service: "cdn",
    component: "cache-invalidation-worker",
    category: "Configuration Error",
  },
  contributing_factors: [
    {
      id: "cf-001",
      title: "No staging environment for CDN configuration changes",
      description:
        "CDN configuration changes are applied directly to production without a staging validation step, removing a critical safety check.",
      category: "process",
      weight: 0.75,
      evidence: [
        "deployment-log-2024-07-15T14:19:44Z",
        "runbook: cdn-config-change lacks staging step",
      ],
    },
    {
      id: "cf-002",
      title: "Regex validation missing in configuration schema",
      description:
        "The cache invalidation API does not validate regex patterns against a known-safe allowlist, allowing arbitrary patterns to be submitted.",
      category: "technical",
      weight: 0.68,
      evidence: ["cdn-api-schema v2.3 — pattern: string (no validation)"],
    },
    {
      id: "cf-003",
      title: "Origin servers not auto-scaled for cold traffic",
      description:
        "Origin server auto-scaling policies were tuned for warm-cache traffic levels. They did not trigger fast enough to absorb the cold-cache surge.",
      category: "technical",
      weight: 0.52,
      evidence: [
        "k8s-hpa: scale-up delay 3min",
        "origin CPU hit 99% within 90s of invalidation",
      ],
    },
  ],
  timeline: [
    {
      id: "tl-001",
      timestamp: new Date(Date.now() - 3 * 60 * 60 * 1000 - 20 * 60 * 1000).toISOString(),
      type: "deployment",
      title: "CDN config change deployed",
      description: "Engineer deployed cache invalidation rule update via CDN management API.",
      service: "cdn",
      severity: "low",
    },
    {
      id: "tl-002",
      timestamp: new Date(Date.now() - 3 * 60 * 60 * 1000 - 18 * 60 * 1000).toISOString(),
      type: "anomaly",
      title: "Cache miss rate surged to 100%",
      description: "All CDN PoPs simultaneously reported 100% cache miss rate after invalidation propagated.",
      service: "cdn",
      severity: "critical",
    },
    {
      id: "tl-003",
      timestamp: new Date(Date.now() - 3 * 60 * 60 * 1000 - 17 * 60 * 1000).toISOString(),
      type: "alert",
      title: "Origin CPU alert fired",
      description: "PagerDuty alert: origin-server CPU > 90% for 2 consecutive minutes.",
      service: "asset-server",
      severity: "high",
    },
    {
      id: "tl-004",
      timestamp: new Date(Date.now() - 3 * 60 * 60 * 1000 - 15 * 60 * 1000).toISOString(),
      type: "incident",
      title: "Incident INC-2039 opened",
      description: "On-call engineer opened P2 incident after PagerDuty alert cluster.",
      service: "web-frontend",
      severity: "high",
    },
    {
      id: "tl-005",
      timestamp: new Date(Date.now() - 3 * 60 * 60 * 1000 - 5 * 60 * 1000).toISOString(),
      type: "config_change",
      title: "Faulty rule rolled back",
      description: "Engineer reverted CDN configuration to previous revision.",
      service: "cdn",
      severity: "medium",
    },
    {
      id: "tl-006",
      timestamp: new Date(Date.now() - 3 * 60 * 60 * 1000).toISOString(),
      type: "recovery",
      title: "Cache warm-up complete — traffic normalizing",
      description: "CDN cache hit rate recovered to 87%. Origin traffic returning to baseline.",
      service: "cdn",
      severity: "low",
    },
  ],
  fix_recommendations: [
    {
      id: "fix-001",
      title: "Revert faulty CDN cache invalidation rule immediately",
      description:
        "Roll back the cache invalidation configuration to the last known good revision using the CDN management API.",
      type: "immediate",
      priority: "critical",
      effort: "low",
      impact: "high",
      steps: [
        "Access the CDN management console or API.",
        "Navigate to Cache Rules → Invalidation Policies.",
        "Identify revision deployed at 14:20 UTC (v47).",
        "Execute rollback to v46: `cdn-cli config rollback --revision=46`.",
        "Monitor cache hit rate — should recover within 5 minutes.",
      ],
      owner: "CDN Platform Team",
      estimated_effort: "15 minutes",
    },
    {
      id: "fix-002",
      title: "Add regex validation to CDN config API",
      description:
        "Implement server-side regex validation in the CDN configuration API to reject patterns that match too broadly (e.g., > 1% of cache keys).",
      type: "short_term",
      priority: "high",
      effort: "medium",
      impact: "high",
      steps: [
        "Define regex pattern allowlist (e.g., must start with `/static/`, must include extension).",
        "Add validation middleware to `POST /api/cdn/invalidation-rules`.",
        "Return 400 with descriptive error if pattern is too broad.",
        "Write unit tests covering valid and invalid patterns.",
        "Deploy to staging and test with faulty pattern.",
      ],
      owner: "CDN Platform Team",
      estimated_effort: "3 days",
    },
    {
      id: "fix-003",
      title: "Add CDN config staging environment",
      description:
        "Create a staging CDN environment that mirrors production topology. All configuration changes must pass staging validation before production promotion.",
      type: "long_term",
      priority: "high",
      effort: "high",
      impact: "high",
      steps: [
        "Provision staging CDN PoPs in 3 regions.",
        "Mirror production cache rules to staging on merge to main.",
        "Add automated smoke tests: hit 1000 URLs, verify cache hit rate > 80%.",
        "Update deployment runbook to require staging sign-off.",
        "Add pipeline gate blocking production deploy if staging tests fail.",
      ],
      owner: "Platform Engineering",
      estimated_effort: "2 weeks",
    },
    {
      id: "fix-004",
      title: "Tune origin auto-scaling for cache miss scenarios",
      description:
        "Update HPA settings for origin servers to scale proactively on CDN miss rate signals, not just CPU.",
      type: "short_term",
      priority: "medium",
      effort: "low",
      impact: "medium",
      steps: [
        "Add CloudWatch metric: CDN cache miss rate to KEDA/HPA.",
        "Set scale-up trigger: miss rate > 20% for 60 seconds.",
        "Reduce scale-up cooldown from 3min to 30s.",
        "Load test with simulated full-cache-miss scenario.",
      ],
      owner: "SRE Team",
      estimated_effort: "1 day",
    },
  ],
  lessons_learned: [
    {
      id: "ll-001",
      category: "prevention",
      title: "Configuration changes need blast-radius estimation",
      description:
        "Before applying any cache rule change, the system should estimate the percentage of cache keys affected and warn if above a threshold.",
      action_items: [
        "Build blast-radius calculator into the CDN config deploy pipeline.",
        "Block deploys that would invalidate > 5% of cache keys without explicit approval.",
        "Add runbook section: estimating CDN change blast radius.",
      ],
    },
    {
      id: "ll-002",
      category: "detection",
      title: "CDN cache miss rate alerting was too slow",
      description:
        "The alert for high cache miss rate had a 2-minute evaluation window, meaning the origin was already overwhelmed before the alert fired.",
      action_items: [
        "Reduce CDN miss rate alert evaluation window to 30 seconds.",
        "Add a synthetic canary that validates cache hit rate every 15 seconds.",
      ],
    },
    {
      id: "ll-003",
      category: "response",
      title: "Rollback procedure was undocumented",
      description:
        "The on-call engineer spent 8 minutes locating the CDN rollback procedure. The runbook pointed to a deprecated internal wiki page.",
      action_items: [
        "Update CDN runbook with step-by-step rollback commands.",
        "Add rollback runbook link directly to PagerDuty alert body.",
        "Test rollback procedure in the next gameday exercise.",
      ],
    },
  ],
  affected_services: ["cdn", "asset-server", "web-frontend"],
  impact_summary:
    "Approximately 23 minutes of degraded static asset loading for 100% of web users. Estimated 18% drop in conversion rate during the impact window. No data loss occurred.",
  executive_summary:
    "At 14:20 UTC, an engineer deployed a CDN cache invalidation rule containing a misconfigured regex pattern. The pattern matched all cached assets rather than the intended CSS files, causing a full cache flush across all 47 CDN PoPs simultaneously. Origin servers were overwhelmed by the resulting traffic surge, causing elevated latency and partial unavailability for the web frontend. The incident was detected at 14:22 UTC via CPU alerts and resolved at 14:50 UTC by rolling back the faulty configuration.",
};

// ─── Learning metrics ─────────────────────────────────────────────────────────

export const MOCK_LEARNING_METRICS: LearningMetrics = {
  total_incidents: 214,
  resolved_incidents: 198,
  avg_resolution_time_minutes: 47,
  avg_confidence_score: 0.84,
  outcome_distribution: {
    correct: 152,
    partially_correct: 32,
    incorrect: 8,
    unknown: 6,
  },
  accuracy_trend: [
    { date: "2024-01-01", accuracy: 0.71, incident_count: 12 },
    { date: "2024-02-01", accuracy: 0.74, incident_count: 15 },
    { date: "2024-03-01", accuracy: 0.76, incident_count: 18 },
    { date: "2024-04-01", accuracy: 0.79, incident_count: 22 },
    { date: "2024-05-01", accuracy: 0.82, incident_count: 28 },
    { date: "2024-06-01", accuracy: 0.84, incident_count: 31 },
    { date: "2024-07-01", accuracy: 0.87, incident_count: 36 },
    { date: "2024-07-15", accuracy: 0.91, incident_count: 14 },
  ],
  agent_performance: [
    { agent_type: "log_analyzer",         avg_confidence: 0.88, run_count: 198, failure_rate: 0.06 },
    { agent_type: "metric_analyzer",      avg_confidence: 0.91, run_count: 201, failure_rate: 0.04 },
    { agent_type: "trace_analyzer",       avg_confidence: 0.84, run_count: 167, failure_rate: 0.09 },
    { agent_type: "dependency_mapper",    avg_confidence: 0.93, run_count: 143, failure_rate: 0.02 },
    { agent_type: "hypothesis_generator", avg_confidence: 0.79, run_count: 156, failure_rate: 0.12 },
    { agent_type: "evidence_collector",   avg_confidence: 0.82, run_count: 142, failure_rate: 0.08 },
    { agent_type: "rca_synthesizer",      avg_confidence: 0.87, run_count: 128, failure_rate: 0.05 },
    { agent_type: "fix_recommender",      avg_confidence: 0.85, run_count: 119, failure_rate: 0.07 },
  ],
};
